# Generated by Django 4.1 on 2024-09-09 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceTicketTriggers',
            fields=[
                ('logger_fk_id', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('logger_name', models.CharField(max_length=7)),
                ('cycle_2_status', models.CharField(blank=True, max_length=20, null=True)),
                ('cycle_2_value', models.FloatField(blank=True, null=True)),
                ('rain_info', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('data_presence', models.FloatField(blank=True, null=True)),
                ('check_data', models.CharField(blank=True, max_length=3, null=True)),
            ],
            options={
                'db_table': 'maintenance_ticket_triggers',
            },
        ),
    ]
